# Create subfolder within the current working directory
dir.create("R")

dir.create("R/DataProcessing")
dir.create("R/DataProcessing/01DataAcquisitionNOAA")
dir.create("R/DataProcessing/02DataAcquisitionUSGSWaterTemp")
dir.create("R/DataProcessing/03DataAcquisitionUSGSWaterFlow")
dir.create("R/DataProcessing/04WaterAnalysis")
dir.create("R/DataProcessing/04WaterAnalysis/AnacostiaRiver")
dir.create("R/DataProcessing/04WaterAnalysis/FoxRiver")
dir.create("R/DataProcessing/04WaterAnalysis/HousatonicRiver")
dir.create("R/DataProcessing/04WaterAnalysis/HudsonRiverAlbany")
dir.create("R/DataProcessing/04WaterAnalysis/Kalamazoo")
dir.create("R/DataProcessing/04WaterAnalysis/PassaicRiver")
dir.create("R/DataProcessing/04WaterAnalysis/Spokane")
dir.create("R/DataProcessing/05PCBProfile")

dir.create("R/Flux")

dir.create("R/Summary")
dir.create("R/Summary/AnacostiaRiver")
dir.create("R/Summary/FoxRiver")
dir.create("R/Summary/HousatonicRiver")
dir.create("R/Summary/HudsonRiverAlbany")
dir.create("R/Summary/Kalamazoo")
dir.create("R/Summary/PassaicRiver")
dir.create("R/Summary/Spokane")

dir.create("Data")
dir.create("Data/AnacostiaRiver")
dir.create("Data/FoxRiver")
dir.create("Data/HousatonicRiver")
dir.create("Data/HudsonRiverAlbany")
dir.create("Data/Kalamazoo")
dir.create("Data/PassaicRiver")
dir.create("Data/Spokane")

dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/AnacostiaRiver")
dir.create("Output/Data/FoxRiver")
dir.create("Output/Data/HousatonicRiver")
dir.create("Output/Data/HudsonRiverAlbany")
dir.create("Output/Data/Kalamazoo")
dir.create("Output/Data/PassaicRiver")
dir.create("Output/Data/Spokane")

dir.create("Output/Plot")
dir.create("Output/Plot/AnacostiaRiver")
dir.create("Output/Plot/FoxRiver")
dir.create("Output/Plot/HousatonicRiver")
dir.create("Output/Plot/HudsonRiverAlbany")
dir.create("Output/Plot/Kalamazoo")
dir.create("Output/Plot/PassaicRiver")
dir.create("Output/Plot/Spokane")

