# Create subfolder within the current working directory
dir.create("R")
dir.create("R/Flux")
dir.create("R/Flux/FoxRiver")
dir.create("R/ReadData")
dir.create("R/Summary")
dir.create("R/Summary/FoxRiver")
dir.create("Data")
dir.create("Data/FoxRiver")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/FoxRiver")
dir.create("Output/Plot")
dir.create("Output/Plot/FoxRiver")
