# Create subfolder within the current working directory
dir.create("R")

dir.create("R/DataProcessing")
dir.create("R/DataProcessing/01DataAcquisitionNOAA")
dir.create("R/DataProcessing/02DataAcquisitionUSGSWaterTemp")
dir.create("R/DataProcessing/03DataAcquisitionUSGSWaterFlow")
dir.create("R/DataProcessing/04WaterAnalysis")
dir.create("R/DataProcessing/04WaterAnalysis/AnacostiaRiver")
dir.create("R/DataProcessing/04WaterAnalysis/FoxRiver")
dir.create("R/DataProcessing/04WaterAnalysis/HousatonicRiver")
dir.create("R/DataProcessing/04WaterAnalysis/HudsonRiver")
dir.create("R/DataProcessing/04WaterAnalysis/KalamazooRiver")
dir.create("R/DataProcessing/04WaterAnalysis/PassaicRiver")
dir.create("R/DataProcessing/04WaterAnalysis/SpokaneRiver")
dir.create("R/DataProcessing/05PCBProfile")

dir.create("R/Flux")

dir.create("Data")
dir.create("Data/AnacostiaRiver")
dir.create("Data/FoxRiver")
dir.create("Data/HousatonicRiver")
dir.create("Data/HudsonRiver")
dir.create("Data/KalamazooRiver")
dir.create("Data/PassaicRiver")
dir.create("Data/SpokaneRiver")

dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/AnacostiaRiver")
dir.create("Output/Data/FoxRiver")
dir.create("Output/Data/HousatonicRiver")
dir.create("Output/Data/HudsonRiver")
dir.create("Output/Data/KalamazooRiver")
dir.create("Output/Data/PassaicRiver")
dir.create("Output/Data/SpokaneRiver")

dir.create("Output/Plot")
dir.create("Output/Plot/AnacostiaRiver")
dir.create("Output/Plot/FoxRiver")
dir.create("Output/Plot/HousatonicRiver")
dir.create("Output/Plot/HudsonRiver")
dir.create("Output/Plot/KalamazooRiver")
dir.create("Output/Plot/PassaicRiver")
dir.create("Output/Plot/SpokaneRiver")

